In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [4]:
a1 +a2

array([ 7,  9, 11, 13, 15])

In [5]:
#BRODCASTING
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [6]:
arr_2 = arr+10
arr_2


array([20, 30, 40, 50])

In [8]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [11]:
#MATRIX MULTIPLICATION
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [12]:
A *B

array([[ 5, 12],
       [21, 32]])

In [14]:
A@B #ACTUAL MATRIX MULTIPLICATION OR USE np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [15]:
#TRANSPOSE
A.T

array([[1, 3],
       [2, 4]])

In [16]:
#STACKING ARRAY
#1) VERTICAL STACK
#2) HORIZONTAL STACK
#3) SIMPLE STACK

In [19]:
a = np.array([1,2, 3,4])
b = np.array([5,6, 7,8])

In [23]:
#1) VERTICAL STACK
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
#2) HORIZONTAL STACK
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#3) SIMPLE STACK
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
#SPLITTING ARRAY
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
#HORIZONTAL SPLIT
np.hsplit(c,2)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [31]:
#VERTICAL SPLIT
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]