In [3]:
import numpy as np

In [4]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a= [1,2,3,4,5,]
a
np.array(a)

array([1, 2, 3, 4, 5])

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr= np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
one = np.zeros(6)
one

array([0., 0., 0., 0., 0., 0.])

In [17]:
two = np.zeros((4,6))
two

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.linspace(0,10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
arr=  np.random.rand(10) #random elemts using randomization  (0 ---> 1)
arr

array([0.17417699, 0.02419485, 0.15782631, 0.47939348, 0.59358788,
       0.97274919, 0.09164229, 0.97472784, 0.07437261, 0.40434669])

In [24]:
arr = np.random.randn(10) #random elements after standerdisation (-3 ---> +3)
arr

array([-0.50754471,  0.55323676,  0.44948558, -0.11694992,  1.07031963,
        0.29346493,  1.20058044,  0.90178094, -0.25981014, -0.0567539 ])

In [5]:
np.random.randint(10,20,10)

array([14, 16, 13, 18, 16, 17, 11, 10, 19, 16], dtype=int32)

In [7]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.dtype

dtype('int64')

In [8]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.shape

(3, 3)

In [9]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.size
arr.max()
arr.min()

9

In [10]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
s= np.sum(arr, axis = 0)
s

array([12, 15, 18])

In [11]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
s= np.sum(arr, axis = 1)
s

array([ 6, 15, 24])

In [12]:
arr.mean()

np.float64(5.0)

In [22]:
arr.sum()

np.int64(80)

In [13]:
arr.std()

np.float64(2.581988897471611)

In [21]:
 arr.argmax()

np.int64(4)

In [18]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[3::2]

array([14, 16, 18, 20])

In [9]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[1,1]

np.int64(7)

In [11]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [12]:
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

In [18]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])